r"""Generate transcript-min.tex: the spoken lines, and nothing else.

transcript.pdf is the working document -- delivery notes, timing table,
backup map, anticipated questions. This is the one you hold while
speaking: for each slide, its number, its title, its time, and the words
you say. No notes, no tables, no Q&A.

    python build_min.py           # regenerate transcript-min.tex
    python build_min.py --check   # fail if it is out of date

Both files come off transcript.md through the same parser as
build_transcript.py -- imported from it rather than reimplemented, so a
character that escapes correctly in one cannot escape differently in the
other, and the two PDFs cannot describe different speech. check_slides.py
runs --check on both.

Unlike transcript.tex this file has no hand-authored preamble to
preserve: it is short enough to carry its own here, so the whole file is
generated and there is no sentinel to edit above.
"""
import importlib.util
import io
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
MD = HERE / "transcript.md"
OUT = HERE / "transcript-min.tex"


def _load_builder():
    """build_transcript.py, without running its main().

    It ends in sys.exit(main()), so a plain import would regenerate
    transcript.tex as a side effect of importing the escaping rules. The
    module text is truncated at that line and executed as a module.
    """
    src = io.open(HERE / "build_transcript.py", encoding="utf-8").read()
    src = src.split("\nsys.exit(main())")[0]
    spec = importlib.util.spec_from_loader("_bt", loader=None)
    mod = importlib.util.module_from_spec(spec)
    mod.__file__ = str(HERE / "build_transcript.py")
    exec(compile(src, str(HERE / "build_transcript.py"), "exec"),
         mod.__dict__)
    return mod


BT = _load_builder()

PREAMBLE = r"""% !TEX root = transcript-min.tex
% =====================================================================
% GENERATED by build_min.py from transcript.md. Do not edit: run
%   python build_min.py
% Speaking copy -- the spoken lines only. transcript.tex is the same
% script with its delivery notes, timing table and Q&A; both are built
% from transcript.md, so they cannot disagree about a word.
%
% Build:
%   latexmk -pdf transcript-min.tex
% =====================================================================
\documentclass[12pt,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[margin=25mm,headheight=15pt]{geometry}
\usepackage{xcolor}
\usepackage{needspace}
\usepackage{microtype}
\usepackage{csquotes}
\usepackage{fancyhdr}
\usepackage[hidelinks,pdftitle={Pre-defense speaking copy},%
  pdfauthor={Md. Sakif Khan}]{hyperref}

\definecolor{agrdark}{RGB}{28,54,78}
\definecolor{agrgrey}{RGB}{110,110,110}
\MakeOuterQuote{"}
\setquotestyle{american}

\hyphenation{WebQSP CWQ ComplexWebQuestions GraphRAG Freebase LangGraph
  McNemar Cypher AGR}

% "ComplexWebQuestions" is on the no-hyphenation list above and is wider
% than the slack in a justified line, so it put a 40pt overfull box in
% the results paragraph. \RaggedRight was worse -- eleven overflows
% instead of one, because ragged setting gives TeX less room to move,
% not more. \emergencystretch lets a bad line stretch its spaces on a
% third pass, which is the intended remedy and costs nothing elsewhere.
\emergencystretch=3em
\tolerance=2000

\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}
\raggedbottom
\clubpenalty=10000
\widowpenalty=10000

\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0.4pt}
\lhead{\small\color{agrgrey}Pre-defense --- speaking copy}
\rhead{\small\color{agrgrey}\thepage}

% A slide's heading. \Needspace keeps a heading from being the last
% thing on a page: a number and a title with the words overleaf is the
% one failure mode that matters in a document read while standing up.
\newcommand{\slidehead}[3]{%
  \Needspace{5\baselineskip}%
  \vspace{4mm}%
  {\color{agrdark}\bfseries\large #1.\ #2}\hfill
  {\color{agrgrey}\small #3}\par
  \vspace{-2mm}{\color{agrgrey}\rule{\linewidth}{0.4pt}}\par
  \vspace{1mm}}

\begin{document}
\thispagestyle{fancy}
{\color{agrdark}\huge\bfseries Pre-defense --- speaking copy}\par
\vspace{2mm}
% \raggedright on this one line: it is two lines of grey subtitle, and
% justifying the first left badness 1924 across it.
{\color{agrgrey}\raggedright Spoken lines only. Delivery notes, timings
and anticipated questions are in \texttt{transcript.pdf}.\par}
\vspace{4mm}
"""


def build():
    md = io.open(MD, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    out, n = [PREAMBLE], 0
    for head, sec in BT.split_sections(md):
        m = re.match(r"(\d+) — (.*?) \*\((\d+:\d\d)\)\*", head)
        if not m:
            continue                     # backup map, Q&A, recovery, delivery
        n += 1
        out.append(f"\\slidehead{{{m.group(1)}}}{{{BT.inline(m.group(2))}}}"
                   f"{{{m.group(3)}}}")
        said = [t for kind, t in BT.blocks(sec) if kind == "speech"]
        for text in said:
            for p in BT.paras(text):
                out.append(BT.wrap(BT.inline(p)) + "\n")
        if not said:
            out.append("\\textit{\\color{agrgrey}(nothing spoken)}\n")
    out.append(r"\end{document}")
    out.append("")
    return "\n".join(out), n


def main():
    text, n = build()
    old = io.open(OUT, encoding="utf-8", newline="").read() \
        if OUT.exists() else ""
    eol = "\r\n" if "\r\n" in old else "\n"
    if "--check" in sys.argv:
        ok = old.replace("\r\n", "\n") == text
        print(("transcript-min.tex is up to date" if ok else
               "STALE -- run: python build_min.py"), f"({n} slides)")
        return 0 if ok else 1
    io.open(OUT, "w", encoding="utf-8", newline="").write(
        text.replace("\n", eol))
    print(f"  transcript-min.tex regenerated: {n} slides")
    return 0


sys.exit(main())
