"""Write journal/supplement/prompts.tex: every prompt template the
systems send, verbatim from the source that sends it.

The thesis reproduces the same thirteen templates in its Appendix A, and
scripts/check_appendix_prompts.py asserts that the appendix still matches
the code. The paper's supplementary material is generated from the code
directly, so it cannot drift; re-run this after any prompt edit and the
supplement follows. Same constants, same modules, same extraction rule as
the appendix checker, so the two documents reproduce one set of strings.

Usage: python scripts/build_paper_supplement.py
Then:  cd journal && latexmk -pdf supplement.tex
"""
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "journal" / "supplement" / "prompts.tex"

# (constant, module, section title, one-line note) in the order a question
# meets them. Mirrors PROMPTS in scripts/check_appendix_prompts.py.
PROMPTS = [
    ("PLANNER_PROMPT", "agr/planner.py", "Planner",
     "Sent once per question unless the planner is removed. The first "
     "exemplar is the single-hop case that is not decomposed."),
    ("SCORE_PROMPT", "agr/scorer.py", "Relation scorer",
     "One batched call per explorer pass over the twenty candidates with "
     "the highest embedding score. Not sent when $\\alpha = 1$."),
    ("EVAL_PROMPT", "agr/nodes.py", "Evaluator",
     "One call per explorer pass. The remaining depth and backtracks are "
     "substituted at send time; no other prompt carries a budget figure."),
    ("DRAFT_PROMPT", "agr/nodes.py", "Drafter and claim decomposer",
     "One call when the search ends. Produces the prose, the answer "
     "entities, and the atomic claims the verifier checks."),
    ("ENTAIL_PROMPT", "agr/nodes.py", "Entailment check",
     "One batched call over the claims neither structural route settled."),
    ("REWRITE_PROMPT", "agr/nodes.py", "Rewriter",
     "One call on the give-up path only. The entity list it is given is "
     "already filtered; its own opinion about entities is discarded."),
    ("ANSWER_PROMPT", "agr/nodes.py", "Answerer (verifier skipped)",
     "Reached only when the drafting call itself failed; no committed run "
     "took this path."),
    ("PROMPT@noretrieval", "agr/baselines/noretrieval.py",
     "No-retrieval control", "The single call of the parametric control."),
    ("PROMPT@vectorrag", "agr/baselines/vectorrag.py",
     "Vector-RAG and static GraphRAG",
     "Shared by the two static retrieval baselines, which differ only in "
     "what they retrieve."),
    ("REL_PRUNE@tog", "agr/baselines/tog.py",
     "Think-on-Graph: relation pruning",
     "One call per frontier entity per depth, over the first $40$ "
     "relations returned."),
    ("ENT_PRUNE@tog", "agr/baselines/tog.py",
     "Think-on-Graph: entity pruning",
     "One call per selected relation per depth, over the first $20$ "
     "neighbours returned."),
    ("SUFFICIENT@tog", "agr/baselines/tog.py",
     "Think-on-Graph: sufficiency",
     "One call per depth, on the last sixty gathered triples."),
    ("ANSWER@tog", "agr/baselines/tog.py", "Think-on-Graph: answer",
     "One call when the search stops, whether it finished or hit the cap."),
]


def extract(module, name):
    """Identical to scripts/check_appendix_prompts.py."""
    src = (ROOT / module).read_text(encoding="utf-8")
    bare = name.split("@")[0]
    m = re.search(rf'^{bare}\s*=\s*"""(.*?)"""', src, re.S | re.M)
    if not m:
        raise SystemExit(f"{name} not found in {module}")
    return re.sub(r"\\\n", "", m.group(1))


def main():
    lines = [
        "% !TEX root = ../supplement.tex",
        "% GENERATED by scripts/build_paper_supplement.py from the source",
        "% files named in each section. Do not edit; re-run the script.",
        "",
    ]
    for const, module, title, note in PROMPTS:
        body = extract(module, const).strip("\n")
        assert "\\end{lstlisting}" not in body
        tex = lambda s: s.replace("_", "\\_")
        lines += [
            f"\\section{{{title}}}",
            f"\\noindent\\textsf{{{tex(module)}}}, constant "
            f"\\textsf{{{tex(const.split('@')[0])}}}. {note} Braces written "
            "\\verb|{like this}| are format fields filled at send time; "
            "doubled braces are literal.",
            "",
            "\\begin{lstlisting}[style=prompt]",
            body,
            "\\end{lstlisting}",
            "",
        ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(PROMPTS)} templates)")


if __name__ == "__main__":
    main()
