"""Generate the data figures and the generated tables from thesis_numbers.json.

The thesis rule is that no reported number is transcribed by hand. A plot is a
reported number in a different notation, so the figures are generated from the
same file the tables read from, rather than drawn against values copied out of
them. Rerun after build_thesis_numbers.py.

The failure histogram is emitted twice, as a figure and as the tabular body of
Table 9.2, because a hand-typed copy of it had drifted: the verifier_fn row
still carried the pre-relabelling counts and the column no longer summed to its
own total. Both now come from the one file.

Writes into thesis_book/figures/:
    fig_accuracy_cost.tex     accuracy against token cost      (Sec 8.7.2)
    fig_hop_strata.tex        Hits@1 by hop stratum            (Sec 8.5)
    fig_failure_histogram.tex failure categories by dataset    (Sec 9.2)
Writes into thesis_book/tables/:
    tab_failure_histogram.tex the same counts as a tabular     (Table 9.2)
    tab_tog_split.tex         the agentic baseline's clipped
                              and unclipped halves             (Table 8.4)

Usage: python scripts/build_figures.py
"""
import argparse
import json
import re
from pathlib import Path

NUMBERS = Path("results/phase4/thesis_numbers.json")
TABDIR = Path("thesis_book/tables")

# Palette. Okabe-Ito, which is colour-blind safe, and chosen so the five series
# also separate by luminance -- a greyscale print keeps them apart even before
# the mark shapes do. Emitted as \definecolor at the top of every figure file so
# the files stay self-contained: the thesis and the slide deck both \input them
# and neither needs a palette in its preamble.
PALETTE = {
    "agrNoRet":  "6E6E6E",   # neutral grey: it is the control, not a treatment
    "agrVector": "E69F00",   # orange
    "agrGraph":  "CC79A7",   # reddish purple
    "agrToG":    "009E73",   # bluish green
    "agrAGR":    "0072B2",   # blue
    "agrWQ":     "0072B2",   # histogram: WebQSP
    "agrCWQ":    "D55E00",   # histogram: CWQ (vermillion)
}
COLOUR_DEFS = "\n".join(
    r"\definecolor{%s}{HTML}{%s}" % (n, v) for n, v in PALETTE.items())

# Display names and per-series marks. Marks carry the distinction on paper; the
# colours carry it on a projector.
SYSTEMS = [
    ("noretrieval", "No-retrieval", "o",         "agrNoRet"),
    ("vectorrag",   "Vector-RAG",   "square",    "agrVector"),
    ("graphrag",    "GraphRAG",     "triangle",  "agrGraph"),
    ("tog",         "Think-on-Graph", "diamond", "agrToG"),
    ("agr",         "AGR",          "*",         "agrAGR"),
]
STRATA = ["h1", "h2", "h3plus"]
STRATUM_LABEL = {"h1": "1 hop", "h2": "2 hops", "h3plus": "3+ hops"}
DATASETS = [("webqsp", "WebQSP"), ("cwq", "ComplexWebQuestions")]

BANNER = ("% GENERATED by scripts/build_figures.py from\n"
          "% results/phase4/thesis_numbers.json -- do not edit.\n")

# None of the emitted files is a document: each is a bare tikzpicture or
# tabular, and building one on its own stops at "Missing \begin{document}".
# The directive sends an editor's build button to the document that \inputs
# it, which also settles the ambiguity of a workspace holding three roots.
# It is emitted here rather than added to the files because the files are
# overwritten every time this script runs.
BOOK_ROOT = "../buetcsepgthesis.tex"


def banner(root):
    return f"% !TEX root = {root}\n{BANNER}"


# The sources in this repository are kept to 80 columns, and generated
# sources are sources: the emitted plots were the only files in thesis_book
# still over it, up to 203 characters on one coordinate list. They are not
# rewrapped after the fact -- a generated file that someone reformats is a
# file that changes back on the next run, and check_slides.py compares each
# one against what this script would write now -- so the fold happens here,
# and every caller returns folded text.
#
# The break points are the ones LaTeX and pgfplots allow: after a top-level
# & in a tabular row, between the ")(" of a coordinate list, after ", " in
# an option list, and before `coordinates` when the option list alone fills
# the line. A delimiter always stays on the left, so a reader scanning the
# first column still sees the first column.
WIDTH = 80


def _depths(s):
    out, d = [], 0
    for ch in s:
        out.append(d)
        d += (ch in "{[") - (ch in "}]")
    return out


def _split(body):
    dep = _depths(body)
    if body.endswith(r"\\") and "&" in body:
        return [i + 1 for i, c in enumerate(body)
                if c == "&" and dep[i] == 0 and (not i or body[i - 1] != "\\")]
    if re.search(r"\)\s+\(", body):
        return [m.start() + 1 for m in re.finditer(r"\)\s+\(", body)]
    return [m.start() + 1 for m in re.finditer(r", ", body) if dep[m.start()]]


def _pack(indent, body):
    """Fill `body` to WIDTH, breaking only where _split allows."""
    cuts = _split(body)
    if not cuts:
        return [indent + body]
    parts, prev = [], 0
    for c in cuts:
        parts.append(body[prev:c].strip())
        prev = c
    parts.append(body[prev:].strip())
    out, cur = [], ""
    for p in [x for x in parts if x]:
        trial = (indent + p) if not cur else cur + " " + p
        if not cur or len(trial) <= WIDTH:
            cur = trial
        else:
            out.append(cur)
            cur = indent + "  " + p
    out.append(cur)
    return out


def fold80(text):
    """Break every emitted line that runs past 80 columns."""
    out = []
    for line in text.split("\n"):
        if len(line) <= WIDTH:
            out.append(line)
            continue
        indent = re.match(r"\s*", line).group(0)
        body = line.strip()
        # An \addplot is two independent things on one line: an option list
        # that breaks at its commas and a coordinate list that breaks
        # between points. Packed separately, because the widest option list
        # here is 96 characters on its own and no coordinate break reaches
        # into it.
        m = re.match(r"(\\addplot\[[^\]]*\])\s+(coordinates\b.*)", body)
        if m:
            out += _pack(indent, m.group(1))
            out += _pack(indent + "  ", m.group(2))
        else:
            out += _pack(indent, body)
    return "\n".join(out)


# Two output targets. The geometry differs because a thesis text column and a
# 16:9 slide are different shapes, and a figure sized for one overflows or
# collides on the other. Everything else -- data, palette, marks -- is shared,
# so both targets are generated from the same JSON by the same code.
#
# legend_drop is the legend's offset in `axis description cs' units, where 1.0
# is the height of the axis RECTANGLE -- not of `height', which pgfplots counts
# inclusive of the tick labels and the xlabel. The rectangle is therefore a good
# deal shorter than `height', and a drop that clears the xlabel in the thesis
# lands squarely on top of it once the figure is shrunk for a slide. It is set
# per target for that reason, and the slide values are the ones that were
# checked against a render rather than reasoned about.
TARGETS = {
    "thesis": dict(
        outdir=Path("thesis_book/figures"),
        root=BOOK_ROOT,
        width=r"0.46\textwidth", height="52mm", gutter="12mm",
        legend_drop=-0.30, strata_legend_drop=-0.30,
        mark_size=2.6, line_mark=2.2,
        hist_width=r"0.80\textwidth", hist_height="95mm", bar_width="4.2mm",
        stack_ticks=False, strata_xlabel=True, hist_tick_font=r"\scriptsize",
    ),
    "presentation": dict(
        outdir=Path("thesis_presentation/figures"),
        # The deck has two documents; the presented one is the default the
        # same way preamble.tex points at it, and the backup deck shares no
        # generated figure with a different geometry.
        root="../pre-defense-0421052099.tex",
        width="52mm", height="34mm", gutter="18mm",
        legend_drop=-0.70, strata_legend_drop=-0.86,
        mark_size=3.0, line_mark=2.6,
        hist_width="112mm", hist_height="62mm", bar_width="3.0mm",
        # A slide panel is 52mm wide and the hop labels read "1 hop (n=256)",
        # which does not fit three across. Break them over two lines -- which
        # costs vertical space, hence the deeper strata_legend_drop.
        stack_ticks=True,
        # ...and once the ticks read "1 hop", "2 hops", "3+ hops", an axis
        # labelled "Hop stratum" says nothing the reader cannot see. Dropping
        # it on the slide buys back the line the stacked ticks cost.
        strata_xlabel=False,
        hist_tick_font=r"\small",
    ),
    "paper": dict(
        outdir=Path("thesis_paper/figures"),
        root="../agr-paper.tex",
        # Sized for elsarticle's single-column `review' measure, which is
        # what gets submitted. Widths are \textwidth-relative so the same
        # files still work if the class options change; only the fixed
        # heights would need revisiting for the publisher's two-column
        # proof, where a column is roughly 3.5in rather than 6in.
        width=r"0.47\textwidth", height="48mm", gutter="10mm",
        legend_drop=-0.34, strata_legend_drop=-0.42,
        mark_size=2.6, line_mark=2.2,
        # Same problem the slide panel has, for the same reason: two
        # 0.47\textwidth panels leave the hop ticks about 55pt each, and
        # "1 hop ($n{=}256$)" needs roughly twice that. On one line the
        # three labels overprinted each other and the right-hand panel's
        # first label collided with the left-hand panel's last across the
        # gutter. Stacking costs a line of depth, hence the deeper
        # strata_legend_drop above.
        stack_ticks=True,
        # ...and stacking pushed "Hop stratum" down onto the legend row,
        # where it overprinted "Vector-RAG" and "Think-on-Graph". The slide
        # target hit this too and the reasoning carries over unchanged: once
        # the ticks read "1 hop", "2 hops", "3+ hops", an axis labelled
        # "Hop stratum" tells the reader nothing the ticks have not.
        strata_xlabel=False,
        # 0.78, not 0.92. pgfplots' `width' is the AXIS width and excludes
        # the y tick labels, which here are twelve typewriter category
        # names -- "premature_termination" is the widest. At 0.92 the
        # picture ran 33.5pt past the measure; the labels are what
        # overflowed, not the bars, so the axis gives way instead.
        hist_width=r"0.78\textwidth", hist_height="88mm", bar_width="3.8mm",
        hist_tick_font=r"\scriptsize",
    ),
}


def legend_below(cfg, drop_key="legend_drop"):
    """One legend for a two-panel figure, centred underneath both panels.
    Placing it inside either panel collides with the data: on WebQSP the curves
    cross the whole plotting area, and on the scatter two systems sit within a
    few tokens of each other. x=1.08 is just past the right edge of the left
    axis, which is the midpoint of the pair once the gutter is counted."""
    return (r"  legend style={at={(1.08,%.2f)}, anchor=north,"
            r" legend columns=5, column sep=1.8mm}," % cfg[drop_key]
            + "\n  legend cell align=left,"
            # The legend keys the systems, not the line styles. Without this
            # the samples inherit WebQSP's dashing and the legend reads as if
            # it applied to the left panel only.
            + "\n  legend image post style={solid},")


def load():
    return json.load(open(NUMBERS, encoding="utf-8"))


# ---------------------------------------------------------------- figure 1
def accuracy_cost(d, cfg):
    """Hits@1 against mean tokens per question, log x, one series per system."""
    by = d["main_results"]["by_system"]
    out = [banner(cfg["root"]), COLOUR_DEFS, r"\begin{tikzpicture}"]
    for i, (ds, ds_label) in enumerate(DATASETS):
        pos = ("" if i == 0 else
               "at={($(plot1.east)+(%s,0)$)}, anchor=west," % cfg["gutter"])
        out += [
            r"\begin{axis}[agrplot, name=plot%d, %s" % (i + 1, pos),
            r"  width=%s, height=%s," % (cfg["width"], cfg["height"]),
            r"  title={%s}," % ds_label,
            r"  xmode=log, log basis x=10,",
            r"  xlabel={Mean tokens per question}, ylabel={Hits@1},",
            r"  xmin=80, xmax=12000, ymin=0.15, ymax=0.85,",
            legend_below(cfg) if i == 0 else "%",
            r"]",
        ]
        for key, label, mark, colour in SYSTEMS:
            r = by[f"{ds}/{key}"]
            out.append(
                r"\addplot[only marks, mark=%s, mark size=%.1fpt, color=%s, "
                r"very thick] coordinates {(%s,%s)};"
                % (mark, cfg["mark_size"], colour,
                   r["mean_tokens"], r["hits_at_1"]))
            if i == 0:
                out.append(r"\addlegendentry{%s}" % label)
        out.append(r"\end{axis}")
    out += [r"\end{tikzpicture}", ""]
    return fold80("\n".join(out))


# ---------------------------------------------------------------- figure 2
def hop_strata(d, cfg):
    """Hits@1 across hop strata. WebQSP's h3plus stratum holds n=4, so every
    series in that panel is drawn dashed and no WebQSP trend should be read as
    interpretable. CWQ, whose smallest stratum is n=49, is drawn solid."""
    by = d["main_results"]["by_hop_stratum"]
    sep = r"\\" if cfg["stack_ticks"] else " "
    out = [banner(cfg["root"]), COLOUR_DEFS, r"\begin{tikzpicture}"]
    for i, (ds, ds_label) in enumerate(DATASETS):
        pos = ("" if i == 0 else
               "at={($(hop1.east)+(%s,0)$)}, anchor=west," % cfg["gutter"])
        ns = [by[f"{ds}/agr"][s]["n"] for s in STRATA]
        out += [
            r"\begin{axis}[agrplot, name=hop%d, %s" % (i + 1, pos),
            r"  width=%s, height=%s," % (cfg["width"], cfg["height"]),
            r"  title={%s}," % ds_label,
            (r"  xlabel={Hop stratum}, ylabel={Hits@1},"
             if cfg["strata_xlabel"] else r"  ylabel={Hits@1},"),
            r"  xtick={0,1,2}, xticklabels={%s},"
            % ", ".join("{%s%s($n{=}%d$)}" % (STRATUM_LABEL[s], sep, n)
                        for s, n in zip(STRATA, ns)),
            r"  xticklabel style={align=center},",
            r"  xmin=-0.25, xmax=2.25, ymin=0, ymax=0.9,",
            legend_below(cfg, "strata_legend_drop") if i == 0 else "%",
            r"]",
        ]
        for key, label, mark, colour in SYSTEMS:
            row = by[f"{ds}/{key}"]
            pts = " ".join(f"({j},{row[s]['hits_at_1']})"
                           for j, s in enumerate(STRATA))
            dash = "dashed, " if ds == "webqsp" else ""
            out.append(r"\addplot[%smark=%s, mark size=%.1fpt, color=%s, "
                       r"very thick] coordinates {%s};"
                       % (dash, mark, cfg["line_mark"], colour, pts))
            if i == 0:
                out.append(r"\addlegendentry{%s}" % label)
        out.append(r"\end{axis}")
    out += [r"\end{tikzpicture}", ""]
    return fold80("\n".join(out))


# ---------------------------------------------------------------- figure 3
def histogram_order(d):
    """Categories with their combined totals, largest first. Ties break on the
    name so the figure and the table cannot end up in different orders."""
    fh = d["failure_histogram"]
    cats = {}
    for ds in ("webqsp", "cwq"):
        for pol in ("wrong", "hedge"):
            for k, v in fh[ds][pol].items():
                if k != "_n":
                    cats[k] = cats.get(k, 0) + v
    return sorted(cats, key=lambda k: (-cats[k], k)), cats


def failure_histogram(d, cfg):
    """Failure categories as stacked bars, wrong and hedge never pooled."""
    fh = d["failure_histogram"]
    order, cats = histogram_order(d)

    def series(ds, pol):
        return " ".join(f"({fh[ds][pol].get(c, 0)},{i})"
                        for i, c in enumerate(order))

    labels = ", ".join(c.replace("_", r"\_") for c in order)
    out = [banner(cfg["root"]), COLOUR_DEFS, r"\begin{tikzpicture}",
           r"\begin{axis}[agrplot,",
           r"  width=%s, height=%s," % (cfg["hist_width"], cfg["hist_height"]),
           r"  xbar stacked, bar width=%s," % cfg["bar_width"],
           r"  xlabel={Questions}, xmin=0, xmax=70,",
           r"  ytick={%s}," % ",".join(str(i) for i in range(len(order))),
           r"  yticklabels={%s}," % labels,
           r"  yticklabel style={font=%s\ttfamily}," % cfg["hist_tick_font"],
           r"  y dir=reverse, ymin=-0.7, ymax=%.1f," % (len(order) - 0.3),
           r"  legend style={at={(0.98,0.05)}, anchor=south east},",
           r"  legend cell align=left, reverse legend=false,",
           r"]"]
    # Hue carries the dataset, tint carries the polarity. Hatching is kept on
    # CWQ so the split survives a greyscale print, where the two hues collapse
    # to similar luminance.
    for ds, ds_label, base, hatch in (
            ("webqsp", "WebQSP", "agrWQ", ""),
            ("cwq", "CWQ", "agrCWQ",
             r", postaction={pattern=north east lines, pattern color=white}")):
        for pol, tint in (("wrong", ""), ("hedge", "!35")):
            out.append(r"\addplot[fill=%s%s, draw=%s!80%s] coordinates {%s};"
                       % (base, tint, base, hatch if pol == "wrong" else "",
                          series(ds, pol)))
            out.append(r"\addlegendentry{%s %s}" % (ds_label, pol))
    out += [r"\end{axis}", r"\end{tikzpicture}", ""]
    return fold80("\n".join(out))


# ----------------------------------------------------------------- table 9.2
def failure_table(d):
    """The tabular body of Table 9.2. A zero prints as an em dash rather than a
    0, because these are counts of observed cases and the dash reads as 'this
    combination did not occur' where a 0 reads as a measurement."""
    fh = d["failure_histogram"]
    order, cats = histogram_order(d)
    cols = [("webqsp", "wrong"), ("webqsp", "hedge"),
            ("cwq", "wrong"), ("cwq", "hedge")]

    def cell(n):
        return "---" if n == 0 else str(n)

    width = max(len(c) for c in order) + 1  # +1 for the escaped underscore
    out = [banner(BOOK_ROOT),
           r"\begin{tabular}{|l|r|r|r|r|r|}",
           r"\hline",
           r"& \multicolumn{2}{c|}{\textbf{WebQSP}} &",
           r"  \multicolumn{2}{c|}{\textbf{CWQ}} & \\",
           r"\hline",
           r"\textbf{Category} & \textbf{wrong} & \textbf{hedge} & "
           r"\textbf{wrong} &",
           r"\textbf{hedge} & \textbf{Total} \\",
           r"\hline"]
    foot = [0, 0, 0, 0]
    for c in order:
        vals = [fh[ds][pol].get(c, 0) for ds, pol in cols]
        foot = [a + b for a, b in zip(foot, vals)]
        out.append("%-*s & %s & \\textbf{%d} \\\\"
                   % (width, c.replace("_", r"\_"),
                      " & ".join("%3s" % cell(v) for v in vals), cats[c]))
    out += [r"\hline",
            r"\textbf{Total} & %s & \textbf{%d} \\"
            % (" & ".join(r"\textbf{%d}" % v for v in foot), sum(foot)),
            r"\hline",
            r"\end{tabular}", ""]

    # The table states its own totals, so it can check them. A column that no
    # longer sums to its footer is exactly the drift this generator replaces.
    for (ds, pol), v in zip(cols, foot):
        assert v == fh[ds][pol]["_n"], (
            f"{ds}/{pol} column sums to {v}, census says {fh[ds][pol]['_n']}")
    return fold80("\n".join(out)), sum(foot)


# ----------------------------------------------------------------- table 8.x
def tog_split_table(d):
    """AGR vs ToG, split on whether the shared call cap cut ToG off."""
    s = d["tog_budget_split"]
    out = [banner(BOOK_ROOT),
           r"\begin{tabular}{|l|l|r|r|r|r|}",
           r"\hline",
           r"\textbf{Dataset} & \textbf{Subset} & \textbf{$n$} & "
           r"\textbf{ToG} & \textbf{AGR} & \textbf{$\Delta$} \\",
           r"\hline"]
    # The delta is taken between the *rounded* columns, not between the full
    # precision values, so that a reader subtracting the two printed numbers
    # gets the printed difference. Differencing first puts WebQSP's clipped row
    # at +0.479 beside columns that read 0.675 and 0.197.
    for ds, label in (("webqsp", "WebQSP"), ("cwq", "CWQ")):
        b = s[ds]
        for key, sub in (("tog_finished", "ToG ran to completion"),
                         ("tog_clipped", "ToG clipped by the cap")):
            r = b[key]
            tog = round(r["tog_hits_at_1"], 3)
            agr = round(r["agr_hits_at_1"], 3)
            out.append(r"%s & %s & %d & %.3f & %.3f & $%+.3f$ \\"
                       % (label if key == "tog_finished" else "", sub,
                          r["n"], tog, agr, agr - tog))
        agg_t = (b["tog_finished"]["n"] * b["tog_finished"]["tog_hits_at_1"]
                 + b["tog_clipped"]["n"] * b["tog_clipped"]["tog_hits_at_1"])
        agg_a = (b["tog_finished"]["n"] * b["tog_finished"]["agr_hits_at_1"]
                 + b["tog_clipped"]["n"] * b["tog_clipped"]["agr_hits_at_1"])
        n = b["n_questions"]
        tog_c = round(agg_t / n, 3)
        agr_c = round(agg_a / n, 3)
        out.append(r"& \emph{combined} & %d & \emph{%.3f} & \emph{%.3f} & "
                   r"$\mathbf{%+.3f}$ \\" % (n, tog_c, agr_c, agr_c - tog_c))
        out.append(r"\hline")
    out += [r"\end{tabular}", ""]
    return fold80("\n".join(out))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", choices=sorted(TARGETS) + ["all"],
                    default="all",
                    help="which geometry to emit (default: all)")
    args = ap.parse_args()
    which = sorted(TARGETS) if args.target == "all" else [args.target]

    d = load()
    TABDIR.mkdir(parents=True, exist_ok=True)
    for target in which:
        cfg = TARGETS[target]
        cfg["outdir"].mkdir(parents=True, exist_ok=True)
        for name, fn in (("fig_accuracy_cost", accuracy_cost),
                         ("fig_hop_strata", hop_strata),
                         ("fig_failure_histogram", failure_histogram)):
            path = cfg["outdir"] / f"{name}.tex"
            path.write_text(fn(d, cfg), encoding="utf-8", newline="\n")
            print(f"wrote {path}  [{target}]")

    # The generated tables belong to the thesis and have no slide variant.
    table, total = failure_table(d)
    path = TABDIR / "tab_failure_histogram.tex"
    path.write_text(table, encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    print(f"  failure histogram totals {total} (thesis states 259)")

    path = TABDIR / "tab_tog_split.tex"
    path.write_text(tog_split_table(d), encoding="utf-8", newline="\n")
    print(f"wrote {path}")
    for ds in ("webqsp", "cwq"):
        b = d["tog_budget_split"][ds]
        print(f"  {ds}: ToG clip rate {b['tog_clip_rate']:.1%}, "
              f"ToG leads by "
              f"{b['tog_finished']['tog_hits_at_1'] - b['tog_finished']['agr_hits_at_1']:+.3f}"
              f" where it finishes")


if __name__ == "__main__":
    main()
