"""Generate Appendix C: the question identifiers every reported number covers.

setup.tex promises that "every question identifier is listed in Appendix C".
Transcribing 880 identifiers by hand would guarantee drift, so the appendix is
written from the sample files themselves and regenerated rather than edited.

Reads  results/phase4/test_webqsp.json, results/phase4/test_cwq.json,
       results/phase3/dev80.json
Writes thesis_book/appendices/samples.tex

Usage: python scripts/build_appendix_samples.py
"""
import json
from collections import Counter
from pathlib import Path

OUT = Path("thesis_book/appendices/samples.tex")
SETS = [
    ("test_webqsp", "results/phase4/test_webqsp.json", "WebQSP test sample"),
    ("test_cwq", "results/phase4/test_cwq.json", "CWQ test sample"),
    ("dev80", "results/phase3/dev80.json", "Development set"),
]


def esc(s):
    return s.replace("_", r"\_")


def load(path):
    return json.load(open(path, encoding="utf-8"))


def strata(rows):
    """The test samples are stratified by hop count, dev80 by question shape."""
    key = ("hop_stratum" if "hop_stratum" in rows[0]
           else "stratum" if "stratum" in rows[0] else "bucket")
    return key, Counter(str(r.get(key)) for r in rows)


def id_block(rows):
    """Identifiers as one flowing, ragged-right paragraph.

    A column layout cannot hold these. A CWQ identifier runs to about 45
    characters and overruns any two-column measure, which is what produced 446
    overfull boxes on the first attempt. Flowing them with an ordinary space
    between items lets TeX fit as many per line as the width allows, and
    \\raggedright stops it stretching the gaps to justify a short last line.
    """
    qids = sorted(r["qid"] for r in rows)
    body = " ".join(esc(q) for q in qids)
    return "{\\raggedright\\ttfamily\\scriptsize\n" + body + "\n\\par}", len(qids)


def main():
    parts = [
        r"\chapter{Sampled Question IDs and Run Manifests}\label{app:samples}",
        "",
        "% GENERATED by scripts/build_appendix_samples.py -- do not edit.",
        "% Rerun the script after any change to the sample files.",
        "",
        "Every number this thesis reports is computed over the question sets "
        "listed here. \\Cref{sec:test-sets} describes how the two test samples "
        "were drawn and certified; this appendix records their contents, so "
        "that a reader can reproduce a reported figure over exactly the "
        "questions it was computed from.",
        "",
        "The identifiers are the dataset's own. A CWQ identifier carries the "
        "WebQSP identifier it was derived from as its prefix, which is why "
        "some of them are long.",
        "",
    ]

    summary = [r"\begin{table}[!htb]", r"  \begin{center}",
               r"    \caption{The three question sets. The test samples are "
               r"stratified by hop count, the development set by question "
               r"shape.}", r"    \label{tab:samples}",
               r"    \small", r"    \begin{tabular}{|l|r|L{83mm}|}",
               r"      \hline",
               r"      \textbf{Set} & \textbf{n} & \textbf{Strata} \\",
               r"      \hline"]
    blocks = []

    for key, path, title in SETS:
        rows = load(path)
        _, st = strata(rows)
        st_txt = ", ".join(f"{esc(k)} {v}" for k, v in sorted(st.items()))
        summary.append(f"      {esc(key)} & ${len(rows)}$ & {st_txt} \\\\")
        summary.append(r"      \hline")

        body, n = id_block(rows)
        blocks.append(
            f"\\section{{{title} "
            f"\\texorpdfstring{{($n = {n}$)}}{{(n = {n})}}}}\n\n"
            f"Source: \\textsf{{{esc(path)}}}.\n\n{body}\n")

    summary += [r"    \end{tabular}", r"  \end{center}", r"\end{table}", ""]
    parts += summary + blocks + [r"\endinput", ""]

    OUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    total = sum(len(load(p)) for _, p, _ in SETS)
    print(f"wrote {OUT} covering {total} question identifiers")
    for key, path, _ in SETS:
        print(f"  {key:12s} {len(load(path)):4d}  {path}")


if __name__ == "__main__":
    main()
