"""Generate the three data figures from results/phase4/thesis_numbers.json.

The thesis rule is that no reported number is transcribed by hand. A plot is a
reported number in a different notation, so the figures are generated from the
same file the tables read from, rather than drawn against values copied out of
them. Rerun after build_thesis_numbers.py.

Writes into thesis_book/figures/:
    fig_accuracy_cost.tex     accuracy against token cost      (Sec 8.6.2)
    fig_hop_strata.tex        Hits@1 by hop stratum            (Sec 8.4)
    fig_failure_histogram.tex failure categories by dataset    (Sec 9.3)

Usage: python scripts/build_figures.py
"""
import json
from pathlib import Path

NUMBERS = Path("results/phase4/thesis_numbers.json")
OUTDIR = Path("thesis_book/figures")

# Display names and per-series marks. Marks carry the distinction on paper.
SYSTEMS = [
    ("noretrieval", "No-retrieval", "o",         "black!55"),
    ("vectorrag",   "Vector-RAG",   "square",    "black!70"),
    ("graphrag",    "GraphRAG",     "triangle",  "black!70"),
    ("tog",         "Think-on-Graph", "diamond", "black!85"),
    ("agr",         "AGR",          "*",         "black"),
]
STRATA = ["h1", "h2", "h3plus"]
STRATUM_LABEL = {"h1": "1 hop", "h2": "2 hops", "h3plus": "3+ hops"}
DATASETS = [("webqsp", "WebQSP"), ("cwq", "ComplexWebQuestions")]

BANNER = ("% GENERATED by scripts/build_figures.py from\n"
          "% results/phase4/thesis_numbers.json -- do not edit.\n")

# One legend for a two-panel figure, centred underneath both panels. Placing it
# inside either panel collides with the data: on WebQSP the curves cross the
# whole plotting area, and on the scatter two systems sit within a few tokens of
# each other. x=1.08 is just past the right edge of the left axis, which is the
# midpoint of the pair once the 12mm gutter is counted.
LEGEND_BELOW = (r"  legend style={at={(1.08,-0.30)}, anchor=north,"
                r" legend columns=5, column sep=1.8mm},"
                "\n  legend cell align=left,"
                # The legend keys the systems, not the line styles. Without
                # this the samples inherit WebQSP's dashing and the legend
                # reads as if it applied to the left panel only.
                "\n  legend image post style={solid},")


def load():
    return json.load(open(NUMBERS, encoding="utf-8"))


# ---------------------------------------------------------------- figure 1
def accuracy_cost(d):
    """Hits@1 against mean tokens per question, log x, one series per system."""
    by = d["main_results"]["by_system"]
    out = [BANNER, r"\begin{tikzpicture}"]
    for i, (ds, ds_label) in enumerate(DATASETS):
        pos = "" if i == 0 else "at={($(plot1.east)+(12mm,0)$)}, anchor=west,"
        out += [
            r"\begin{axis}[agrplot, name=plot%d, %s" % (i + 1, pos),
            r"  title={%s}," % ds_label,
            r"  xmode=log, log basis x=10,",
            r"  xlabel={Mean tokens per question}, ylabel={Hits@1},",
            r"  xmin=80, xmax=12000, ymin=0.15, ymax=0.85,",
            LEGEND_BELOW if i == 0 else "%",
            r"]",
        ]
        for key, label, mark, colour in SYSTEMS:
            r = by[f"{ds}/{key}"]
            out.append(
                r"\addplot[only marks, mark=%s, mark size=2.6pt, color=%s] "
                r"coordinates {(%s,%s)};"
                % (mark, colour, r["mean_tokens"], r["hits_at_1"]))
            if i == 0:
                out.append(r"\addlegendentry{%s}" % label)
        out.append(r"\end{axis}")
    out += [r"\end{tikzpicture}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- figure 2
def hop_strata(d):
    """Hits@1 across hop strata. The h3plus point for WebQSP has n=4 and is
    plotted dashed, so the figure cannot be read as if it were interpretable."""
    by = d["main_results"]["by_hop_stratum"]
    out = [BANNER, r"\begin{tikzpicture}"]
    for i, (ds, ds_label) in enumerate(DATASETS):
        pos = "" if i == 0 else "at={($(hop1.east)+(12mm,0)$)}, anchor=west,"
        ns = [by[f"{ds}/agr"][s]["n"] for s in STRATA]
        out += [
            r"\begin{axis}[agrplot, name=hop%d, %s" % (i + 1, pos),
            r"  title={%s}," % ds_label,
            r"  xlabel={Hop stratum}, ylabel={Hits@1},",
            r"  xtick={0,1,2}, xticklabels={%s},"
            % ", ".join(f"{STRATUM_LABEL[s]} ($n{{=}}{n}$)"
                        for s, n in zip(STRATA, ns)),
            r"  xmin=-0.25, xmax=2.25, ymin=0, ymax=0.9,",
            LEGEND_BELOW if i == 0 else "%",
            r"]",
        ]
        for key, label, mark, colour in SYSTEMS:
            row = by[f"{ds}/{key}"]
            pts = " ".join(f"({j},{row[s]['hits_at_1']})"
                           for j, s in enumerate(STRATA))
            dash = "dashed, " if ds == "webqsp" else ""
            out.append(r"\addplot[%smark=%s, mark size=2.2pt, color=%s, "
                       r"thick] coordinates {%s};" % (dash, mark, colour, pts))
            if i == 0:
                out.append(r"\addlegendentry{%s}" % label)
        out.append(r"\end{axis}")
    out += [r"\end{tikzpicture}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- figure 3
def failure_histogram(d):
    """Failure categories as stacked bars, wrong and hedge never pooled."""
    fh = d["failure_histogram"]
    cats = {}
    for ds in ("webqsp", "cwq"):
        for pol in ("wrong", "hedge"):
            for k, v in fh[ds][pol].items():
                if k != "_n":
                    cats[k] = cats.get(k, 0) + v
    order = sorted(cats, key=lambda k: -cats[k])

    def series(ds, pol):
        return " ".join(f"({fh[ds][pol].get(c, 0)},{i})"
                        for i, c in enumerate(order))

    labels = ", ".join(c.replace("_", r"\_") for c in order)
    out = [BANNER, r"\begin{tikzpicture}",
           r"\begin{axis}[agrplot,",
           r"  width=0.80\textwidth, height=95mm,",
           r"  xbar stacked, bar width=4.2mm,",
           r"  xlabel={Questions}, xmin=0, xmax=70,",
           r"  ytick={%s}," % ",".join(str(i) for i in range(len(order))),
           r"  yticklabels={%s}," % labels,
           r"  yticklabel style={font=\scriptsize\ttfamily},",
           r"  y dir=reverse, ymin=-0.7, ymax=%.1f," % (len(order) - 0.3),
           r"  legend style={at={(0.98,0.05)}, anchor=south east},",
           r"  legend cell align=left, reverse legend=false,",
           r"]"]
    # Shade carries polarity, hatching carries dataset. Using shade alone would
    # give WebQSP-wrong and CWQ-wrong the same fill, and a reader could not see
    # where one dataset's contribution to a bar ends and the other's begins.
    for ds, ds_label, hatch in (("webqsp", "WebQSP", ""),
                                ("cwq", "CWQ",
                                 r", postaction={pattern=north east lines}")):
        for pol, fill in (("wrong", "black!62"), ("hedge", "black!18")):
            out.append(r"\addplot[fill=%s, draw=black!70%s] coordinates {%s};"
                       % (fill, hatch, series(ds, pol)))
            out.append(r"\addlegendentry{%s %s}" % (ds_label, pol))
    out += [r"\end{axis}", r"\end{tikzpicture}", ""]
    return "\n".join(out)


def main():
    d = load()
    OUTDIR.mkdir(parents=True, exist_ok=True)
    for name, fn in (("fig_accuracy_cost", accuracy_cost),
                     ("fig_hop_strata", hop_strata),
                     ("fig_failure_histogram", failure_histogram)):
        path = OUTDIR / f"{name}.tex"
        path.write_text(fn(d), encoding="utf-8", newline="\n")
        print(f"wrote {path}")

    total = sum(v for ds in ("webqsp", "cwq") for pol in ("wrong", "hedge")
                for k, v in d["failure_histogram"][ds][pol].items() if k != "_n")
    print(f"  failure histogram totals {total} (thesis states 259)")


if __name__ == "__main__":
    main()
